# Generated by Django 2.2 on 2019-11-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='team',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
    ]
